apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
  name: example-jgroups-site
spec:
  type: LoadBalancer
  ports:
    - port: 7900
      protocol: TCP
  selector:
    app: example-jgroups
